# Generated by Django 5.2.3 on 2025-06-26 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USPapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='sms_consent',
            field=models.BooleanField(default=False),
        ),
    ]
